### ISSUE TITLE
Are those templates in the https://github.com/projectdiscovery/nuclei-templates repo?

### ISSUE THREAD

**Issue by wellencamass** [geeknik/the-nuclei-templates#8]
Hello, @geeknik !

First of all thats for contributing your work to the community.

Are the templates listed in this repo also pushed to the projectdiscovery repo or they are unique?

Trying to find out if there are unneeded duplicates :)

**Comment by geeknik** [comment]
Some of these are in the community repo, and those versions should take precedence as i’ve been a bit lazy in keeping this repo updated.
